### ISSUE TITLE
pkg_resources.DistributionNotFound:

### ISSUE THREAD

**Issue by leirbag28** [goldstar611/chirp-appimage#9]
Now the 7th? Version that does not work this may be a new Error.  PLEASEfix this. I have made effort to report this and thr previos 5 or 6 versions which also did not work and had a similar error. This is for the Appimage 20240524 version but the rest had a similar issue. (Ubuntu 18.04.6 64bit Intel)

Traceback (most recent call last):
  File "/tmp/.mount_Chirp-xvlL5F/usr/bin/chirp", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/tmp/.mount_Chirp-xvlL5F/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/tmp/.mount_Chirp-xvlL5F/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/tmp/.mount_Chirp-xvlL5F/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/tmp/.mount_Chirp-xvlL5F/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/tmp/.mount_Chirp-xvlL5F/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/tmp/.mount_Chirp-xvlL5F/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'suds' distribution was not found and is required by chirp

**Comment by goldstar611** [comment]
Hi, I’m currently on vacation. I’ll look into this when I have some time! Thanks for being patient

**Comment by jbmoss1982** [comment]
I'm receiving this same error when running the current latest release (20240606) on Arch with kernel 6.9.4. Installing the latest available python-suds 1.4.2.0-3 package had zero effect as well.

**Comment by leirbag28** [comment]
Yep....and as of today (06-14-24) this new version 20240614 doesn't work either. Goldstar emailed me about 2 versions back and said he is working on it, but now I wonder Why even release these last 2 if they don't work? Hopefully this gets fixed as I need Tidradio H3 updates or enhancements of the CHIRP software with it as it not quite perfectly working.

**Comment by leirbag28** [comment]
Goldstar... I am not sure what is going on but This problem still persists even with today's release 20240618. I see fixes being made (which are actually pointless at this time as the app doesn't work to begin with. In other words it seems OTHER fixes are being made to an app that doesn't work in the first place.....I think they should be made AFTER.

**Comment by ergotu** [comment]
@leirbag28 Pretty sure the releases in this repo are automated and just pull the latest commit from upstream when it runs, the last commit in this repo was 4 months ago. So basically, you see the fixes from upstream, not from goldstar. Goldstar said he'd look into it when he has time, so just be patient.

**Comment by leirbag28** [comment]
@ergotu Thanks for the repsonse. I don't know if I understand what releases in the repo are automated means (a computer automatically goes through submitted errors and fixes them?) but no matter.... at least I partly understand why releases are being released.

**Comment by goldstar611** [comment]
Hi @ergotu @leirbag28 @jbmoss1982,

I intend to take a look at this issue soon. My main development machine power supply (which is a proprietary form-factor unfortunately) has failed which has prevented me from being more responsive.

**Comment by leirbag28** [comment]
Awesome!

**Comment by goldstar611** [comment]
This was a python 3.8 vs 3.10 issue which disappeared after I upgraded the repos used from focal to jammy.

This should be fixed in the latest release.

**Comment by jbmoss1982** [comment]
Chirp launches but still getting Python errors.

[chirp.appimage.python.error.log.txt](https://github.com/user-attachments/files/18304755/chirp.appimage.python.error.log.txt)
![chirp appimage python error](https://github.com/user-attachments/assets/51f0815c-8670-427d-b5c7-5501f59dda0a)
